### ISSUE TITLE
 Could not dispatch event

### ISSUE THREAD

**Issue by abalta** [Anadea/RxBus#5]
Hi, I added your library to my project. 

In fragment register bus onCreate method. Then I create event method for subsribe an event like this.
`@Subscribe
    public void removeMatchedUser(MatchedResult result) {
        Timber.tag("BUS").i("REMOVE USER: " + result.getUser().getUsername());
        Timber.tag("BUS").i("SIZE BEFORE: " + mMatchedResultList.size());
        removeAndNotify(result);
    }
`
In my activity, I post my event like this.
`rxBus.post(matchedResult);`

I need to remove result event from my list and notify the dataset of adapter.

**Comment by jjhesk** [comment]
same to me,    Process: com.emperor.cinemasappdev, PID: 17199
                                                                           java.lang.RuntimeException: Could not dispatch event: class com.zyntauri.gdnet.ui.uievents.PaymentEvent
                                                                               at com.anadeainc.rxbus.AbstractSubscriber.accept(AbstractSubscriber.java:32)
                                                                               at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
                                                                               at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:198)
                                                                               at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:250)
                                                                               at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:234)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by dubroff** [comment]
Hi, jjhesk.
Perhaps in the method subscribed to an PaymentEvent, you have bug and the method execution finished with exception.
